# Development-specific configuration
# This file overrides settings in _config.yml for local development

baseurl: ""
url: "http://localhost:4000"

# Show drafts in development
show_drafts: true

# More verbose output
verbose: true

# Don't minify in development
sass:
  style: expanded